/**********************************************************************
 * LeechCraft - modular cross-platform feature rich internet client.
 * Copyright (C) 2013  Slava Barinov <rayslava@gmail.com>
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/

#include "twitterprotocol.h"
#include <QIcon>
#include <QApplication>
#include <QSettings>
#include "twitteraccount.h"


namespace LeechCraft
{
namespace Azoth
{
namespace Woodpecker
{

	TwitterProtocol::TwitterProtocol (ICoreProxy_ptr proxy, Plugin *plugin)
	: QObject (plugin)
	, Proxy_ (proxy)
	, Plugin_ (plugin)
	{
		QSettings settings (QCoreApplication::organizationName (),
				QCoreApplication::applicationName () + "_Azoth_Woodpecker");
		settings.beginGroup ("Accounts");
		for (const auto& id : settings.childKeys ())
		{
			const auto& data = settings.value (id).toByteArray ();
			if (auto acc = TwitterAccount::Deserialize (data, this, proxy))
				AddAccount (acc);
		}
		settings.endGroup ();
	}

	QObject* TwitterProtocol::GetQObject ()
	{
		return this;
	}

	IProtocol::ProtocolFeatures TwitterProtocol::GetFeatures () const
	{
		return PFNone;
	}

	QList<QObject*> TwitterProtocol::GetRegisteredAccounts ()
	{
		QList<QObject*> result;
		for (auto acc : Accounts_)
			result << acc;
		return result;
	}

	Plugin* TwitterProtocol::GetParentProtocolPlugin () const
	{
		return Plugin_;
	}

	QString TwitterProtocol::GetProtocolName () const
	{
		return tr ("Twitter");
	}

	QIcon TwitterProtocol::GetProtocolIcon () const
	{
		static QIcon icon ("lcicons:/azoth/woodpecker/resources/images/twitter.svg");
		return icon;
	}

	QByteArray TwitterProtocol::GetProtocolID () const
	{
		return "Woodpecker.Twitter";
	}

	QList<QWidget*> TwitterProtocol::GetAccountRegistrationWidgets (IProtocol::AccountAddOptions)
	{
		return {};
	}

	void TwitterProtocol::RegisterAccount (const QString& name, const QList<QWidget*>& widgets)
	{
		auto acc = new TwitterAccount (name, this, Proxy_, QByteArray ());
		saveAccount (acc);
		AddAccount (acc);
	}

	QWidget* TwitterProtocol::GetMUCJoinWidget ()
	{
		return nullptr;
	}

	void TwitterProtocol::RemoveAccount (QObject *accObj)
	{
		auto acc = qobject_cast<TwitterAccount*> (accObj);

		QSettings settings (QCoreApplication::organizationName (),
				QCoreApplication::applicationName () + "_Azoth_Woodpecker");
		settings.beginGroup ("Accounts");
		settings.remove (acc->GetAccountID ());
		settings.endGroup ();

		emit accountRemoved (accObj);

		Accounts_.removeAll (acc);

		acc->deleteLater ();
	}

	void TwitterProtocol::AddAccount (TwitterAccount *acc)
	{
		Accounts_ << acc;
		emit accountAdded (acc);

		connect (acc,
				SIGNAL (accountChanged (TwitterAccount*)),
				this,
				SLOT (saveAccount (TwitterAccount*)));
	}

	void TwitterProtocol::saveAccount (TwitterAccount *account)
	{
		QSettings settings (QCoreApplication::organizationName (),
				QCoreApplication::applicationName () + "_Azoth_Woodpecker");
		settings.beginGroup ("Accounts");
		settings.setValue (account->GetAccountID (), account->Serialize ());
		settings.endGroup ();
	}
}
}
}
