
/**********************************************************************
 * LeechCraft - modular cross-platform feature rich internet client.
 * Copyright (C) 2006-2013  Slava Barinov
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/

#include "twittermessage.h"
#include "twitterentry.h"

namespace LeechCraft
{
namespace Azoth
{
namespace Woodpecker
{
  TwitterMessage::TwitterMessage (Direction dir, IMessage::Type type, TwitterEntry *entry)
	: QObject (entry)
	, Entry_ (entry)
	, Type_ (type)
	, Dir_ (dir)
	{
	}

	QObject* TwitterMessage::GetQObject ()
	{
		return this;
	}

	void TwitterMessage::Send ()
	{
		Entry_->Send (this);
		Store ();
	}

	void TwitterMessage::Store ()
	{
		Entry_->Store (this);
	}

	qulonglong TwitterMessage::GetID () const
	{
		return ID_;
	}

	void TwitterMessage::SetID (qulonglong id)
	{
		ID_ = id;
		emit messageDelivered ();
	}

	bool TwitterMessage::IsRead () const
	{
		return IsRead_;
	}

	void TwitterMessage::SetRead ()
	{
		IsRead_ = true;
	}

	IMessage::Direction TwitterMessage::GetDirection () const
	{
		return Dir_;
	}

	IMessage::Type TwitterMessage::GetMessageType () const
	{
		return Type_;
	}

	IMessage::SubType TwitterMessage::GetMessageSubType () const
	{
		return IMessage::SubType::Other;
	}

	QObject* TwitterMessage::OtherPart () const
	{
		return Entry_;
	}

	QString TwitterMessage::GetOtherVariant () const
	{
		return "";
	}

	QString TwitterMessage::GetBody () const
	{
		return Body_;
	}

	void TwitterMessage::SetBody (const QString& body)
	{
		Body_ = body;
	}

	QDateTime TwitterMessage::GetDateTime () const
	{
		return TS_;
	}

	void TwitterMessage::SetDateTime (const QDateTime& timestamp)
	{
		TS_ = timestamp;
	}

	bool TwitterMessage::IsDelivered () const
	{
		return ID_ != static_cast<qulonglong> (-1);
	}

	QString TwitterMessage::GetRichBody () const
	{
		return RichBody_;
	}

	void TwitterMessage::SetRichBody (const QString& body)
	{
		RichBody_ = body;
	}
}
}
}
